### ISSUE TITLE
Object as props value not working

### ISSUE THREAD

**Issue by harit2101** [TroyAlford/react-jsx-parser#18]
Am using react-jsx-parser for converting html/xml data in react js element. Only issue  am facing is while passing some object data . Its is converted into string.
Example : 
 "<customElement data=['1','2','3']></customElement>"

For above component if I use the parser then it is returning the props data as string ..

**Comment by TroyAlford** [comment]
For this kind of binding, I do think we should add support for the object-syntax binding. Even so - the right syntax would be:

`<customElement data={['1', '2', '3']}>` (note the `{}` surrounding the array).

Another way to get around this, for now, would be to add the `data` property to the `JsxParser`'s `bindings` prop. Example:

```
const html = "<customElement />"
const bindings = {
    data: ['1', '2', '3'],
}

<JsxParser html={html} bindings={bindings} />
```

Whatever you put in the `bindings` prop will be passed as props to all custom elements rendered within the `JsxParser`'s rendering process. Does that work for your case? Or do you need to embed the binding in the string?

**Comment by harit2101** [comment]
@Troy - **Thanks a lot** for your quick response. I don't think that binding would help in my case. 
I have a string containing nested components in XML/HTML format. For example see below.

let  stringData= **"<parentComponent title='Parent'><childComponent dataArray=['1','2','3'] dataObject ={ name : 'harit' , age: '26'}> </childComponent></parentCompenent>**

<JsxParser components={[ parentComponent ,
                                            childComponent ]}
                   jsx={stringData}
/>

Am directly passing the string to the parser. I can't fetch the props from string and passing to every component is not the good idea .

**Comment by TroyAlford** [comment]
Ok. I have a branch I'm experimenting with that will support this.
Unfortunately the package size is 10x as big :(

Either way, you will need to wrap non string prop values in curly braces,
as I showed in my above comment.

You might consider also just parsing the strings, using JSON.parse within
your components? Then you could pass strings in, and have it work?

**Comment by harit2101** [comment]
@TroyAlford  - Passing within curly braces didn't worked. 
Components are frame work  level components so I cant edit its logic for handling props as string and 
 later JSON.parse on it :-(

Any help or reference would be really helpfull..Thanks in advance

**Comment by TroyAlford** [comment]
Unfortunately, we aren't fully settled on a solution for this yet, for this package. In the meantime, I suggest you do something like:

**TranslatorA.js**
```javascript
import React, { Component } from 'react'
import CustomElement from 'external-package' // the actual component you want to render

export default class CustomElementTranslator extends Component {
    render() {
        // Pass in a stringified prop value, and then parse it within this wrapper component
        const myProperty = JSON.parse(this.props.myProperty)
        return (<CustomElement myProperty={myProperty} />)
    }
}
```

Now, wherever you're using `<JsxParser ... />`, use it like:
```javascript
import JsxParser from 'react-jsx-parser'
import CustomElementTranslator from './path/to/customElementTranslator'
...

<JsxParser 
  components={{ customElement: CustomElementTranslator }}
  jsx={jsx}
/>
```

Because you've mapped it in this way, your JSX can contain something like:
```
<h1>Some header</h1>
<customElement myProperty="['1', '2', '3']" />
```

When it gets parsed, your wrapper, `CustomElementTranslator` will actually be passed the props - and will intelligently parse the string-version using `JSON.parse()` - then pass the parsed version (now an `Array`) to the actual component you want to render.

(Note - I have not tested the above code, and I haven't added any error-handling or anything, which you probably would want to do for a production scenario)

**Comment by TroyAlford** [comment]
Closing this. :) Please let me know if you need any more help, ok?

**Comment by harit2101** [comment]
Hey,
@TroyAlford Thanks a lot for your effortand. Sorry for the long silence. Still that object issue is not working plus I noticed one more issue. Please see below

1) Object still not supported in jsx as props value . Even not rendering the tag in dom at all. Its just skipping the component completely and even the rest component/tag next to it. If I remove the props ,then its working fine. 

`
let htmlString = <Component icon = "warning" myArray={[1,2,3]} myObj={{ foo: 'bar' }} ></Component>

<JsxParser components={ { Component } }
                   jsx={htmlString }
/>
`

2) Its not working if we pass attribute without value .Previously it was working fine . Now if I add any attribute without value then its doesn't render the component plus remaining rest component below it.
In below example see attribute 'inline' and 'noicon'

let htmlString = <Component noicon  inline tooltip="testing"></Component>

**Comment by harit2101** [comment]
Hey,

One Simple check solved my all problem. I have added below check in **version 0.0.12** .

added below method to check for JSON value 

```
IsJsonString(str) {
    try {
        JSON.parse(str);
    } catch (e) {
        return false;
    }
    return true;
}
```

Calling this method inside the parseAttr() method,added one more if condition like below

```
else if(this.isJsonString(value)){
 value = JSON.parse(value);
}
```

Have a look , if you think it is helpful , kindly add it to the module.
Thanks alot

**Comment by TroyAlford** [comment]
@harit2101 - understood that properties which are formatted as `name={value}` are not working. That is because the current version is parsing as `application/xhtml+xml` - and properties with `{}` surrounded values are not valid xhtml+xml. The workaround I proposed above is designed to allow you to get past that - did you try it?

I'm intending to release a new version soon which will have a more robust, acorn-jsx based parser that should handle most of the issues you're experiencing. At that time, there will be 2 separate components to choose from, and you'll want the second one. (I may be able to get to it tonight or this weekend)

The catch on props which have a name but no value is a good one - those should evaluate to `true`. I'll open a fresh issue for this.

I don't like the approach of `try/catch` to check for JSON. Doing this may work for one case, but create problems in another. It causes the parser to assume that just because a property value can be parsed as JSON, it should - and that's not a safe assumption. Someone could be intentionally passing a string which happens to contain JSON, but intending to keep it as a string (such as the string `'true'`, the string `'null'`, or the string `'0'` - which would have a meaningfully different value and meaning if parsed).

**Comment by harit2101** [comment]
Hi,

Was messed up with some other stuff, didn't got chance to look into the latest release.  Will test and update you soon, may be by tomorrow. 

Thanks a lot for explaining the issue of using try/catch.  Surely it will create an issue if user wants string to be displayed . :-)

Though of updating you about one minor difference i noticed in creation of react component when there  are not children inside it.

Suppose below is the component 

`<myComponent></myComponent>`

It has no children
With out JSX parser the output of **this.props.children** is **undefined**.
If I pass this component through jsx parser the output is array object. Empty array.

As I have already said not tested in latest release but noticed difference in v0.0.12.

**Comment by TroyAlford** [comment]
I went ahead and updated/released the refactor. Unfortunately, the package size increased - but I believe the majority of the issues you have reported should be resolved as of `1.1.0`.

**Comment by harit2101** [comment]
Hey,

Object as props value is now working but after correcting one typo error. That is in switch case check **'JSXExpressionContainer' instead of 'JSXExpressionContainer'.**

tried with below component syntax

`<component tooltip={ [ { age : '25' , name : ' harit ' }, { age : '26' , name : ' Troy ' } ] } >`

No children issue is still exist. Which I have addressed in my yesterdays chat.  Returning empty array instead of **undefined**

**Comment by TroyAlford** [comment]
Releasing 1.1.1 in a moment, which should resolve both issues. Let me know if you see anything else!
